Use window resurrection
TanStack/virtual pull request #210
Opened 2021-11-01 21:59 UTC by AndyDyer

resurrecting #80  since the original author last had activity on it in Jan 2021

2021-11-10 14:03 UTC, Andrey-Bazhanov commented
Hi @tannerlinsley, please take a look on this PR.  There are lot peoples waiting for this feature.

2021-11-10 14:14 UTC, centrodph approved these changes

2021-11-17 13:26 UTC, Zertz commented
For what it's worth, I switched our `react-table` implementation from `react-window` + `react-window-scroller` to this branch and it  works very well! I was even able to remove a couple hacks that were necessary before. 👌

2021-11-19 14:11 UTC, Zertz commented
I needed build artifacts to use this so I forked and published this PR on npm under [react-virtual-window-fork](https://www.npmjs.com/package/react-virtual-window-fork), with hopefully clear attribution to @tannerlinsley, @AndyDyer and @petersendidit

Hopefully this gets merged eventually 🙏

2021-11-19 15:02 UTC, piecyk reviewed
Overall looks good. Wondering now, as this is a low level hook, do we want to include it? On other hand useVirtualWindow is pretty common case 🤔

2021-11-29 20:49 UTC, tannerlinsley commented
This PR is up next. Looking through it now.

2021-11-29 20:54 UTC, tannerlinsley commented
I'd love to get everyone to put their 👀 on this PR one last time and see if we could possibly rethink the way we support the window element. It *seems* like we should have almost all of the utilities and abstractions we need to make this happen with fewer changes. Any ideas?

- Could we simply pass different hooks and elements to `useVirtual`?

2021-11-29 20:54 UTC, tannerlinsley requested changes

2021-11-29 20:54 UTC, tannerlinsley commented on src/useWindowRect.js
> +export default function useWindowRect(windowRef) {
At the very least, let's make this change. I'm concerned with the added bundle size for this addition, so it's a good start.

2021-11-29 22:38 UTC, piecyk commented
> Could we simply pass different hooks and elements to useVirtual?

I think we could, maybe like this https://github.com/tannerlinsley/react-virtual/pull/219

2021-11-29 23:37 UTC, AndyDyer commented
> > Could we simply pass different hooks and elements to useVirtual?
> 
> I think we could, maybe like this #219

I like this

2021-11-30 02:29 UTC, Zertz commented
For what it's worth, it would be extremely useful to have a single hook that can handle both use cases. We have a virtual table component that, for various reasons, must include both element-relative and window-relative "modes" and having separate hooks means we set one to the actual data size and the other to zero. This works but it would be neat if we could switch between these modes just by conditionally swapping the reference element.

Either way, great work everyone and I'll happily take whichever API you pick! 🎉

2021-11-30 05:19 UTC, piecyk commented
> For what it's worth, it would be extremely useful to have a single hook that can handle both use cases.

Having `useScroll` abstraction, it would be possible to write that, for example one option could look like, imho much more flexible

```jsx
 const rowVirtualizer = useVirtual({
  size: rows.length,
  parentRef,
  useScroll: props => {
    const elementRes = useElementScroll(props)

    const windowRes = useWindowScroll({ ...props, windowRef: React.useRef(window) }),

    return isWindow ? windowRes : elementRes
  }
})
```

2021-11-30 07:58 UTC, piecyk commented
To directly support window scroll, we need to have some kind of boolean in which mode is the useVirtual, for example isWindow, and the ref to window, windowRef. 

```tsx
const rowVirtualizer = useVirtual({
  size: rows.length,
  parentRef,
  isWindow,
  windowRef: React.useRef(window),
})
  ```
  
fyi Update the #219 to include those changes, build on top of useScroll

2021-11-30 12:48 UTC, Zertz commented
Would it be possible for `parentRef` and `windowRef` to be mutually exclusive and then use that internally to determine the mode we're in?

2021-11-30 13:12 UTC, piecyk commented
> Would it be possible for parentRef and windowRef to be mutually exclusive and then use that internally to determine the mode we're in?

Yes, as windowRef is optional, we can check if `windowRef !== undefined` to determine if in window scroll mode.

2021-11-30 13:47 UTC, circlingthesun commented
> > Would it be possible for parentRef and windowRef to be mutually exclusive and then use that internally to determine the mode we're in?
> 
> Yes, as windowRef is optional, we can check if `windowRef !== undefined` to determine if in window scroll mode.

Surely you can just pass a window ref as the parentRef and do a check inside to hook to determine if its a window ref ( `parentRef.current === window` )? That'll save you two parameters. I did exactly that here: https://github.com/circlingthesun/react-virtual/blob/master/index.tsx#L44

2021-11-30 14:22 UTC, piecyk commented
@circlingthesun what about scrollToIndex? Using `parentRef` we can calculate the offset of the list and correctly scroll to index. Imho having explicit windowRef is better in long run.

2021-11-30 14:35 UTC, circlingthesun commented
@piecyk useRect was also updated see: https://github.com/circlingthesun/react-virtual/blob/master/use-rect.tsx#L6.

2021-11-30 14:39 UTC, circlingthesun commented
I've been running this in production for over a year and scrollToIndex works, at least for my purposes. I was going to make a PR but my fork was based on a previous version and, at the time, it seemed like the previous PR was about to be accepted. I prefer a less complex interface. I'm just raising this to point out another approach.

2021-12-01 14:28 UTC, piecyk commented
Guys the #219 is ready for review, as mention before imho `useScroll` is very flexible, and allow to change the default implementation very easy. Tested the window scroll with dynamic list/grid and works pretty good.

2021-12-01 21:23 UTC, AndyDyer commented
> Surely you can just pass a window ref as the parentRef and do a check inside to hook to determine if its a window ref ( `parentRef.current === window` )? That'll save you two parameters. I did exactly that here: https://github.com/circlingthesun/react-virtual/blob/master/index.tsx#L44

This makes total complete sense and definitely slims down the API

2021-12-01 22:25 UTC, tannerlinsley commented
This looks fantastic. Any way we could get a simple test set up for this? Even if it doesn't go super deep, I just want to make sure things at least render with the new hook.

2021-12-02 02:17 UTC, piecyk commented
@AndyDyer we need the parentRef to recognise where it's in page, and take it under account when scrolling.

@tannerlinsley added some simple tests 🙈

2021-12-02 17:58 UTC, tannerlinsley commented
Awesome. I merged the other PR, so this should be ready to fix up

2022-01-20 17:28 UTC, tannerlinsley commented
I think we might need to point this PR at the `next` branch or just open a new PR. If no one responds here otherwise, I'll close this PR in a few days.

2022-04-14 12:08 UTC, lironezra commented
Hi Guys,

Anyone knows what going on with this issue?
There is another way to achieve the virtual scrolling with `window` ref?

Thanks!!!

2022-06-03 00:16 UTC, tannerlinsley commented
This PR is outdated and should either be closed, re-architected or rebased against v3 beta. Thanks!

2022-06-03 00:16 UTC, closed without merging

2023-11-08 19:53 UTC, epurban commented
Hey @tannerlinsley, is this window scrolling functionality attainable currently?

2023-11-11 12:39 UTC, piecyk commented
> Hey @tannerlinsley, is this window scrolling functionality attainable currently?

@epurban yes it is in latest beta, you can use the `useWindowVirtualizer`