Improves readability
TanStack/virtual pull request #826
Opened 2024-09-02 10:01 UTC by schalkventer

I had to re-read this sentence a several times until I understood the meaning. Perhaps adding punctuation and chaning the grammar sligthly improves readability?

2024-09-02 12:22 UTC, piecyk requested changes

2024-09-12 04:37 UTC, schalkventer commented on docs/api/virtualizer.md
> +An optional function that (if provided) should implement the scrolling behavior for your scrollElement. It will be called with the following: An offset to scroll towards; a boolean indicating whether
Sounds good!

2024-09-12 04:45 UTC, schalkventer commented
@piecyk: See changes above.

2024-09-16 14:17 UTC, piecyk approved these changes

2024-09-16 14:18 UTC, merged

2024-09-16 14:18 UTC, piecyk commented
@schalkventer thanks!